add solution for task 03-accordion without arrow
js-tasks-ru/htmlcss-20230227_yaroshenkoannette pull request #7
Opened 2023-03-08 22:07 UTC by YaroshenkoAnna

2023-03-08 22:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-09 13:55 UTC, GSemikozov requested changes

2023-03-09 13:55 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    max-width: 730px;
лишнее ограничение

2023-03-09 13:55 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin: 0 auto;
марджины не задаем

2023-03-09 13:55 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        <p class="accordion__content">
контент может быть не только текстовым, поэтому - лучше div

2023-03-09 18:14 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-09 18:41 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-10 09:33 UTC, GSemikozov requested changes

2023-03-10 09:33 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-top: 8px;
наверно margin-bottom?)

2023-03-10 09:39 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-10 15:08 UTC, GSemikozov approved these changes

2023-03-10 15:09 UTC, merged